# Einführung in Python, Numpy und ein paar Tipps

Dieses Notebook soll als Mini-Tutorial eine Einführung in Python und einige in diesem Kurs verwendete Libraries und Tools geben. Vielen davon wirst du in nachfolgendem Assignments immer wieder begegnen.<br>

Grundätzlich gibt es Textblöcke und Codeblöcke, wobei die Codeblöcke eine in Text eingebettete Möglichkeit zum Coden bieten. Alles was in ihnen steht, ist ganz normaler Python-Code.
<div class="alert alert-block alert-info">
Die <b>blauen Kästen</b> sind Infokästen. Meist handelt es sich hier um weiterführendes Wissen oder Hinweise, die aber nicht unbedingt relevant für die Bearbeitung der Aufgaben innerhalb des Notebooks sind.
</div>
<div class="alert alert-block alert-warning">
Die <b>orangenen Kästen</b> sind immer Hinweise auf Kurzaufgaben. Unter ihnen befinden sich i.d.R. freie Codeblöcke, innerhalb welcher Aufgaben bearbeitet werden sollen.
</div>

In [130]:
# Code-Spielplatz
# in diesen Codeblocks direkt unter den orangenen Blöcken kannst du dich austoben

***

## 1. "Hello, World!" ##
Aber beginnen wir mal bei den Basics. So würde beispielsweise "Hello, World!" in Python aussehen:

In [131]:
print("Hello, World!")

Hello, World!


Ziemlich einfach oder?

## 2. Variablen deklarieren und deren Handling 

### 2.1 Variablen deklarieren

Anders als in vielen anderen Programmiersprachen müssen in Python keine Variablentypen deklariert werden. der Datentyp wird erst durch das zuweisen eines Wertes bestimmt:

In [132]:
a = 2
b = 'Ich möchte 1000 BlueROVS'
print('a ist vom Typ: ', type(a), ' mit dem Wert: ', a)
print('b ist vom Typ: ', type(b), ' mit dem Wert: ', b)

a ist vom Typ:  <class 'int'>  mit dem Wert:  2
b ist vom Typ:  <class 'str'>  mit dem Wert:  Ich möchte 1000 BlueROVS



__Pro Tipp: F-Strings__ <br> Meistens ist es besser, mit sogenannten F-Strings, auch Format-Strings genannt, zu arbeiten, da diese im Vergleich zu den herkömmlichen Strings u.a. das direkte Einbinden von Variablen oder Ausdrücken innerhalb des Strings erlauben: <br>

<code> print(f'a ist vom Typ: {type(a)} mit dem Wert {a}') </code><br>

Der große Vorteil ist, dass **single quotes** nur einmal vorkommen und auf Variablen mit **geschweiften Klammern** verwiesen werden kann.

<div class="alert alert-block alert-warning">
<b>🔽 Jetzt Du: 🔽</b> <br>
Probiere in dem Codeblock direkt hier drunter <b>F-Strings</b> aus, initialisiere andere Variablentypen und schaue, was passiert, wenn du das Skript erneut ausführst. <br>
Dafür kannst du entweder oben unter der Navigation auf <b>"Run All"</b> klicken,<br>
<left><img src="figures/excecuteall.png" width="300"><br>
oder auf das <b>Dreieck ▷ links</b> neben dem Codeblock selbst :D<br>
<left><img src="figures/excecutecell.png" width="200">
</div>

In [133]:
# Code-Spielplatz

### 2.2 Rechenoperationen

funktionieren genauso wie in den meisten Programmiersprachen mit
 - Addition `+`
 - Subtraktion `-`
 - Multiplikation `*`
 - Division `/`.

In [134]:
# mit ** kann man Werte exponentieren

Ergebnis = 3**2 * 2
print(Ergebnis)

18


Soweit die Basics.
## 3. ✨ Numpy ✨ ##
<div class="alert alert-block alert-info">
<b>Du hast schonmal mit Matlab gearbeitet? </b> Dann könnte für dich folgende Website interessant sein: <a href="https://numpy.org/doc/stable/user/numpy-for-matlab-users.html">NumPy for Matlab Users</a> <br>
Hier werden tabellarisch äquivalente Codebeispiele aufgeührt und die relevanten Unterschiede beider Sprachen hervorgehoben.
</div>
Anders als in vielen anderen Programmiersprachen, bietet die Standardbibliothek von Python keine expliziten Array-Datentypen. Üblicherweise wird mit Listen gearbeitet, um Arrays darzustellen.
Deshalb gibt es <b><code>NumPy</b></code> (Numerical Python), eine zusätzliche Bibliothek, die wir in diesem Kurs nutzen wollen. Sie eignet sich insbesondere beim Umgang mit großen Datenmengen, da Operationen schneller ausgeführt werden und Speicherplatz effizienter genutzt wird. Zudem bietet <code>NumPy</code> eine umfangreiche Funktionenbibliothek für statistische, algebraische und mathematische Operationen auf Arrays, was die Notwendigkeit von expliziten Schleifen in vielen Fällen eliminiert und den Code sauberer und schneller macht.

<div class="alert alert-block alert-info">
Online gibt es eine sehr detaillierte Dokumentation über alle Funktionalitäten der Bibliothekselemente mit Codebeispielen. Grundsätzlich lohnt es sich oft, schnell in der Doku nachzuschauen, wenn man sich bei der Syntax oder Inputvariablen nicht sicher oder wenn man nach einem bestimmten Element sucht<br>
<a href="https://numpy.org/doc/stable/reference/routines.array-creation.html">NumPy Documentation</a> <br>
Alternativ kann man auch mit der Maus über der Funktion fahren, dann sieht man mögliche Inputs der Funktion.
</div>

Damit wir alle Vorteile von Numpy nutzen können, müssen wir es erstmal importieren:

In [135]:
import numpy

Diese Zeile Code braucht man innerhalb eines Dokuments nur einmal und man schreibt sie in der Regel ganz an den Anfang.<br>
Jetzt können wir auch schon loslegen:

In [136]:
# einfacher NumPy Array in Zeilenform
Zeilenvektor = numpy.array([1, 2, 3, 4, 5])

# Matrizen definieren
Matrix1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Matrix2 = numpy.array([[1, 0], [0, 0]])

</div>
<div class="alert alert-block alert-warning">
<b>🔽 Jetzt Du: 🔽</b><br>
Mit <b>@</b> kann man <b>Matrizen multiplizieren</b>. Probiere das unten mal aus, indem Du eine neue <code>Matrix3</code> entsprechender Größe definerst, um sie dann anschließend mit <code>Matrix1</code> zu multiplizieren.
</div>

In [137]:
# Code-Spielplatz


__Pro Tip: Libraries richtig benutzen__ <br> 
Dir ist bestimmt aufgefallen, dass oben vor allen Elementen aus der Numpy Bibliothek immer ein <code>numpy.</code> steht. Das scheint auf Dauer doch ein bisschen nervig oder?<br>
Das geht __einfacher__ mit 

<code>import numpy as np</code>,<br>

wobei <code>np</code> (theoretisch) auch durch beliebige andere Abkürzungen bzw. "Alias" ersetzt werden kann. Nachfolgend kann man auf die Bibliothek vereinfacht zugreifen: <code>np.name</code>

<div class="alert alert-block alert-warning">
<b>🔽 Jetzt Du: 🔽</b><br>
Importiere <code>numpy</code> unter dem Alias <code>np</code>!
</div>

In [138]:
# Code-Spielplatz

import numpy as np # wieder weg machen am Ende

<div class="alert alert-block alert-info">
Wenn nur auf einzelne Elemente einer Bibliothek zugegriffen werden soll, kann es sinnvoll sein, diese explizit zu importieren: <br>
<code>from numpy import sinc, pi</code> In diesem Fall <code>sinc()</code> (Sinus-Funktion) und <code>pi</code>. Der große Vorteil ist, dass <code>sinc()</code> und <code>pi</code> nun direkt aufgerufen werden können, ohne dass es den Namen der Bibliothek bedarf
</div>

<div class="alert alert-block alert-warning">
<b>🔽 Jetzt Du: 🔽</b> <br>
 Wie würde man die Inverse der folgenden Matrix berechnen?<br>
 Hinweis: online Doku über NumPy <a href="https://numpy.org/doc/stable/reference/routines.array-creation.html">NumPy Documentation</a> <br>
</div>

In [139]:
# Code-Spielplatz

# np.random.rand(rows,col) generiert eine zufällige Matrix einer definierten Größe
A = np.random.rand(3,3)
print(f'A = {A}')

A_inv = A # hier kann etwas noch nicht stimmen
print(f'A invertiert ist A_inv = {A_inv}')

A = [[0.9106921  0.40968204 0.22405833]
 [0.20839944 0.79802743 0.34206401]
 [0.0371613  0.87943682 0.21238706]]
A invertiert ist A_inv = [[0.9106921  0.40968204 0.22405833]
 [0.20839944 0.79802743 0.34206401]
 [0.0371613  0.87943682 0.21238706]]


Jetzt haben wir die **mächtigen Tools** von Numpy so angeteasert, aber das wirkt ja bisher noch nicht so wild. Also jetzt hier nachfolgend eine winzige Auswahl

In [140]:
# ARRAY MIT NULLEN DER DIMENSION 2X3
Nullmatrix = np.zeros((2, 3))

# ARRAY MIT EINSEN DER DIMENSION 2X4
Einsmatrix = np.ones((2, 4))

# RRAY MIT EINSEN AUF DER DIAGONALEN UND SONST NULLEN
Eye = np.eye(3,3)

# ARRAY EINER BESTIMMTEN GRÖẞE OHNE INITIALISIERTE EINTRÄGE
Empty = np.empty((2,3))

# ARRAZ MIT 50 ÄQUIDISTANTEN WERTEN ZWISCHEN 0 UND 5
t = np.linspace(0, 5, 50)

# EINZELNE ELEMENTE AUSLESEN
print(f'Das erste Element in Matrix1 ist {Matrix1[0,0]} und wird mit dem Index 0 aufgerufen')
print(f'Der letzte Element in Matrix1 ist {Matrix1[-1,-1]} bzw. {Matrix1[2,2]}')


Das erste Element in Matrix1 ist 1 und wird mit dem Index 0 aufgerufen
Der letzte Element in Matrix1 ist 9 bzw. 9


In [141]:

# ELEMENTWEISE MULTIPLIZIEREN/RECHNEN
print(f'Die elementweise Multiplikation von Matrix1 und Eye ist {Matrix1*Eye}')
    #(zur Erinnerung: mit @ reguläre Matrizenmultiplikation)

Die elementweise Multiplikation von Matrix1 und Eye ist [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


In [142]:
# APPEND
    # create a new row
new_row = np.array([[10, 11, 12]])
    # append new_row to Matrix1
print(np.append(Matrix1, new_row, axis=0)) 
    # "axis=0" definiert die Achse, entlang welcher neue Elemnte hinzugefügt werden sollen
    # bei Weglassung dieses Arguments wird der gesamte Array zu einem Reihenvektor "platt gemacht"
print(np.append(Matrix1, new_row))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 4. **if else** und **for loops**

### 4.1 **if else**

In Python ermöglichen if-else-Bedingungen, dass verschiedene Codeblöcke basierend auf der Wahrheit einer Bedingung ausgeführt werden. Während `if else` klar macht, dass nur einer der beiden Blöcke ausgeführt wird, führen mehrere unabhängige `if`-Bedingungen dazu, dass jede Bedingung separat überprüft wird. Das kann in bestimmten Fällen ineffizienter sein.
Hier ist ein einfaches Beispiel für `if else`, das überprüft, ob eine Zahl positiv, negativ oder null ist:

In [143]:
zahl2 = 10

if zahl2 > 0:
    print(f'Die Zahl {zahl2} ist positiv')
elif zahl2 < 0:
    print(f'Die Zahl {zahl2} ist negativ')
else:
    print(f'Die Zahl {zahl2} ist negativ oder null')

Die Zahl 10 ist positiv


Das `elif` steht für `else if` und kann theoretisch beliebig oft benutzt werden.

### 4.2 **for loops**

In Pyhton iterieren `for`-loops über Listen/Arrays, weshalb die Syntax in der Regel so aussieht:

In [144]:
words = np.array((['a', 'big', 'water', 'tank']))

for i in words:
    print(i)


a
big
water
tank


<div class="alert alert-block alert-info">
Wenn man ganz normal über ein Zahlenreihe mit einem Start- und Endwert iterieren möchte, geht das natürlich auch. Und zwar mit <code> for i in range(startwert, endwert): ...</code>.
</div>

**Pro Tip: enumerate**
Mit `enumerate` kann man Elemente aus einem Array bzw. aus einer Liste nummerieren und diese in einem neuen Array/Liste als Tupel abspeichern.

In [148]:
words_enum = enumerate(words)
print(list(words_enum))
# Nummerierung bei 2 starten (default ist 0)
print(list(enumerate(words, 2)))

l1 = list(words_enum)


# Iteration und Zugriff auf das erste Tupel
for index, word in enumerate(words):
    print(index, word)


[(0, 'a'), (1, 'big'), (2, 'water'), (3, 'tank')]
[(2, 'a'), (3, 'big'), (4, 'water'), (5, 'tank')]
0 a
1 big
2 water
3 tank


enumerate und append verbinden mit if und for (Aufgabe für Studis)

**Pro Tip: list comprehensions**

+ kleine Aufgabe

###  how to code? Plan steps, consider working your way up by starting with simpler problem, write sufficient comments (abschließender Tipp am ENde)

## am Ende nochmal Übersicht von allen Rechenoperationen, KOnventionen etc erneuter Verweis auf Numpz for Matlab users

***
other
- objektorientierte programmierung
- callback(listener)
- als aufgabe 0 integrieren
- referenz auf objekte (beispiel vielleicht)
- Funktionen deklarieren
- reshape doch mit reinnehmen, da in assignment 2?
- pip install numpy

In [146]:


fruits = ['apple', 'banana', 'cherry']
enum_fruits = enumerate(fruits)
 
next_element = next(enum_fruits)
print(f"Next Element: {next_element}")

next_element2 = next(enum_fruits)
print(f"Next Element: {next_element2}")


Next Element: (0, 'apple')
Next Element: (1, 'banana')


In [147]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(list(enumerate(matrix)))

for i, col in enumerate(matrix):
    for j, value in enumerate(col):
        print(f"Matrix[{i}][{j}] = {value}")


[(0, [1, 2, 3]), (1, [4, 5, 6]), (2, [7, 8, 9])]
Matrix[0][0] = 1
Matrix[0][1] = 2
Matrix[0][2] = 3
Matrix[1][0] = 4
Matrix[1][1] = 5
Matrix[1][2] = 6
Matrix[2][0] = 7
Matrix[2][1] = 8
Matrix[2][2] = 9
