# Introduction to Python, Numpy & some useful tips

This notebook serves as a mini-tutorial to introduce Python and some of the libraries and tools used in this course. You will encounter many of them repeatedly in the following assignments.<br>

In this notebook, there are text blocks and code blocks, with the code blocks providing a way to code directly within the text. Everything within them is just regular Python code.
<div class="alert alert-block alert-info">
The blue boxes are <b>info</b> boxes. They usually contain additional knowledge or tips that are not necessarily relevant for completing the tasks in the notebook.
</div> 
<div class="alert alert-block alert-warning">
The orange boxes always indicate <b>short tasks</b>. Below them, you will usually find empty code blocks where you should complete the tasks.
</div>

In [26]:
# Python Playground
# TODO Code & Conquer - Unleash your inner coding warrior and dominate the digital realm one line of Python at a time!

***

## 1. "Hello, World!" ##
But let's start with the basics. This is what “Hello, World!” would look like in Python:

In [27]:
print("Hello, World!")

Hello, World!


Easy peasy!

## 2. Declaring variables and their handling 

### 2.1 Declaring variables

Unlike in many other programming languages, no variable types need to be declared in Python. The data type is only determined by assigning a value:

In [28]:
a = 2
b = 'I want 1000 BlueROVS'
print('a is of type: ', type(a), ' with the value: ', a)
print('b is of type: ', type(b), ' with the value: ', b)

a is of type:  <class 'int'>  with the value:  2
b is of type:  <class 'str'>  with the value:  I want 1000 BlueROVS



__Pro Tip: F-Strings__ <br> Usually, it's better to use F-Strings, also known as format strings, because they allow you to directly embed variables or expressions within the string, unlike traditional strings: <br>

<code> print(f'a is of type: {type(a)} with the value {a}') </code><br>

The big advantage is that <b>single quotes '...'</b> only appear once, and variables can be referenced using <b> curly braces {...}</b>.

<div class="alert alert-block alert-warning"> <b>🔽 Your Turn: 🔽</b> <br><br>
Try using <b>F-Strings</b> in the code block right below, initialize different variable types, and see what happens when you run the script again. <br> You can either click on <b>"Run All"</b> in the navigation above,<br> <left><img src="figures/excecuteall.png" width="300"><br> or on the <b>triangle ▷ on the left</b> next to the code block itself :D<br> <left><img src="figures/excecutecell.png" width="200"> </div>

In [29]:
# Python Playground

### 2.2 Arithmetic operations

work in the same way as in most programming languages with
 - addition `+`
 - subtraction `-`
 - multiplication `*`
 - division `/`.

In [30]:
# With ** you can raise values to a power

solution = 3**2 * 2
print(solution)

18


So much for the basics.
## 3. ✨ Numpy ✨ ##
<div class="alert alert-block alert-info">
<b>You have already worked with Matlab before? </b> In that case the following website could be quite helpful for you <a href="https://numpy.org/doc/stable/user/numpy-for-matlab-users.html">NumPy for Matlab Users</a> <br>
Equivalent code examples are listed here in tabular form and the relevant differences between the two languages are highlighted.
</div>

Unlike many other programming languages, Python's standard library does not provide explicit array data types. Instead, lists are typically used to represent arrays.

That’s why we have <b><code>NumPy</code></b> (Numerical Python), an additional library that we will use in this course. It is particularly useful when dealing with large datasets, as operations are executed faster and memory is used more efficiently. Additionally, <code>NumPy</code> offers an extensive library of functions for statistical, algebraic, and mathematical operations on arrays, which eliminates the need for explicit loops in many cases and makes the code cleaner and faster.

<div class="alert alert-block alert-info"> There is very detailed documentation online on all the functionalities of the library elements with code examples. It is generally worthwhile to quickly check the documentation if you're unsure about the syntax or input variables, or if you're looking for a specific element.<br> <a href="https://numpy.org/doc/stable/reference/routines.array-creation.html">NumPy Documentation</a> <br> Alternatively, you can also hover your mouse over the function to see possible inputs for the function. </div></br>
To take full advantage of NumPy, we first need to import it:

In [31]:
import numpy

You only need this line of code once within a document, and it is usually written right at the beginning. <br>
Now, we can get started:

In [32]:
# Simple NumPy array in row form
row_vector = numpy.array([1, 2, 3, 4, 5])

# Defining matrices
matrix1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = numpy.array([[1, 0], [0, 0]])

<div class="alert alert-block alert-warning"> 
<b>🔽 Your Turn: 🔽</b><br>
With <b>@</b> you can <b>multiply matrices</b>. Try it out below by defining a new <code>matrix3</code> of appropriate size, and then multiply it with <code>matrix1</code>. 
</div>

In [33]:
# Python Playground

__Pro Tip: Using Libraries Properly__ <br>
You’ve probably noticed that every element from the NumPy library above is always prefixed with <code>numpy.</code>. That seems a bit annoying in the long run, right? <br>
There’s an __easier__ way by using:

<code>import numpy as np</code>,<br>

where <code>np</code> (theoretically) can be replaced by any other abbreviation or "alias." From then on, you can access the library more easily: <code>np.name</code>

<div class="alert alert-block alert-warning"> 
<b>🔽 Your Turn: 🔽</b><br>
Import <code>numpy</code> using the alias <code>np</code>!
</div>

In [34]:
# Python Playground

import numpy as np


<div class="alert alert-block alert-info"> 
If you only need to access specific elements of a library, it can be useful to import them explicitly: <br>
<code>from numpy import sinc, pi</code> In this case, <code>sinc()</code> (sine function) and <code>pi</code>. The big advantage is that <code>sinc()</code> and <code>pi</code> can now be called directly without needing the library name.
</div> 
<div class="alert alert-block alert-warning">
<b>🔽 Your Turn: 🔽</b> <br>
Calculate the inverse of the following matrix.<br>
Check the online documentation for NumPy for help: <a href="https://numpy.org/doc/stable/reference/routines.array-creation.html">NumPy Documentation</a> <br>
</div>

In [35]:
# python playground

# np.random.rand(rows, cols) generates a random matrix of a defined size
A = np.random.rand(3,3)
print(f'A = {A}')

A_inv = A # this doesn't seem right yet
print(f'the inverse of A is A_inv = {A_inv}')

A = [[0.19349149 0.76060183 0.34009777]
 [0.61047732 0.51594503 0.16481241]
 [0.73588801 0.43895396 0.78696637]]
the inverse of A is A_inv = [[0.19349149 0.76060183 0.34009777]
 [0.61047732 0.51594503 0.16481241]
 [0.73588801 0.43895396 0.78696637]]


Now that we’ve teased the **powerful tools** of NumPy, it doesn’t seem all that impressive just yet. So, here’s a tiny selection to showcase its capabilities:

In [36]:
# ARRAY WITH ZEROS OF DIMENSION 2X3
zero_matrix = np.zeros((2, 3))

# ARRAY WITH ONES OF DIMENSION 2X4
ones_matrix = np.ones((2, 4))

# ARRAY WITH ONES ON THE DIAGONAL AND ZEROS ELSEWHERE
eye_matrix = np.eye(3, 3)

# ARRAY OF A CERTAIN SIZE WITH UNINITIALIZED ENTRIES
empty_matrix = np.empty((2, 3))

# ARRAY WITH 50 EQUALLY SPACED VALUES BETWEEN 0 AND 5
t = np.linspace(0, 5, 50)

# ACCESSING INDIVIDUAL ELEMENTS
print(f'The first element in matrix1 is {matrix1[0, 0]} and is accessed with index 0')
print(f'The last element in matrix1 is {matrix1[-1, -1]} or {matrix1[2, 2]}')



The first element in matrix1 is 1 and is accessed with index 0
The last element in matrix1 is 9 or 9


In [37]:

# ELEMENTWISE MULTIPLICATION
print(f'the elementwise multiplication of matrix1 and eye_matrix is {matrix1*eye_matrix}')
    #(as a reminder: regular matrix multiplication with @)

the elementwise multiplication of matrix1 and eye_matrix is [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


In [38]:
# APPEND
    # create a new row array
new_row = np.array([[10, 11, 12]])
    # append new_row to Matrix1
print(np.append(matrix1, new_row, axis=0)) 
    # “axis=0” defines the axis along which new elements are to be added
    # if this argument is omitted, the entire array is “flattened” into a single row vector

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 4. **if else** and **for loops**

### 4.1 **if else**

In Python, if-else conditions allow different blocks of code to be executed based on the truth of a condition. While `if else` makes it clear that only one of the two blocks will be executed, multiple independent `if` conditions result in each condition being checked separately. This can be more inefficient in certain cases.
Here is a simple example of `if else` that checks whether a number is positive, negative or zero:

In [39]:
number = 10

if number > 0:
    print(f'the number {number} is positive')
elif number < 0:
    print(f'the number {number} is negative')
else:
    print(f'the number {number} is negative or zero')

the number 10 is positive


The `elif` stands for `else if` and can theoretically be used as often as you like.

### 4.2 **for loops**

In Pyhton, `for` loops iterate over lists/arrays, which is why the syntax usually looks like this:

In [40]:
words = np.array((['a', 'big', 'water', 'tank']))

for i in words:
    print(i)


a
big
water
tank


If you want to iterate over a numerical sequence with a starting and ending value, you can simply do so using `for i in range(start_val, last_val): ...`.

## 5. **enumerate**
With `enumerate` you can enumerate elements from an array or a list and save them in a new array/list as a tuple.

In [41]:
words_enum = enumerate(words)
print(list(words_enum))

[(0, np.str_('a')), (1, np.str_('big')), (2, np.str_('water')), (3, np.str_('tank'))]


In [42]:
# start the enumeration at 2 (default is 0)
print(list(enumerate(words, 2)))

[(2, np.str_('a')), (3, np.str_('big')), (4, np.str_('water')), (5, np.str_('tank'))]


In [43]:
# Iteration and accessing the first tuple
for index, word in enumerate(words):
    print(index, word)

0 a
1 big
2 water
3 tank


## 6. Functions
Among other advvantages, functions allow you to write code once and reuse it multiple times without repeating it and help break a large problem into smaller, manageable parts, making the code easier to understand, debug, and maintain.

<div class="alert alert-block alert-warning">
<b>🔽 Your Turn: 🔽 </b><br><br>

Write a function, that extracts all <b>zeros</b> and <b>twos</b> out of the array <code> measure_data </code> and adds them to a new array <code> reduced_data </code> while enumerating them. At the end, print <code> reduced_data </code> with the numbers and the corresponding count.

</div>

In [45]:
# Python Playground

# define reduced_data
reduced_data = np.array([])

# define function to process data
def my_function(measures):
    global reduced_data
    for i, value in enumerate(measures[0]):
        if value == 0 or value == 2:
            reduced_data = np.append(reduced_data, value)



# Measure data array
measure_data = np.array([[0, 2, 3 ,5 ,1 ,0 ,4 ,3 ,2 ,0 ,1, 9, 6, 7, 8]])

# call the function
my_function(measure_data)

# print reduced_data and count its entrys along the way
for index, val in enumerate(reduced_data, 1):
    print(index, val)

1 0.0
2 2.0
3 0.0
4 2.0
5 0.0


## 7. list comprehensions

*"List comprehensions are like the Pythonic way of saying, 'Why take the long way around when you can just teleport to your destination?'"*

Here ist a quick example why

In [ ]:
# Traditional way using a for loop
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
squared_evens = []

for num in numbers:
    if num % 2 == 0:
        squared_evens.append(num ** 2)

print(squared_evens)

In this snippet, the goal is to square every even number of an original list `numbers` and save those squared numbers in a new list `squared_evens`.
<div class="alert alert-block alert-info"> 
You may have noticed that the syntax for <code>.append()</code> is slightly different here as opposed to <code>np.append</code>. That is because <code>.append()</code> ist more convenient when working with lists.
</div> 

And here comes the magic of list comprehensions: with just **one simple line of code** (instead of 4) we can accomplish the same thing:

In [ ]:
# Simplified version using list comprehension
SQUARED_EVENS = [num ** 2 for num in numbers if num % 2 == 0]

print(SQUARED_EVENS)

As you can see, list comprehensions are concise, allowing you to perform tasks in a single line, making the code cleaner and easier to read. Despite their brevity, they clearly express the operation, and they are often more efficient than traditional loops due to their optimization for such tasks.

<div class="alert alert-block alert-warning">
<b>🔽 Your Turn: 🔽 </b>

Convert a list of distances from feet to metres using list comprehension if the original distance is equal to or below 100 ft.
</div>

**Hint:** the formula for transferring distances from feet to metres is:
$$ [m] = {{[ft]} \over 3.281} $$

In [54]:
# python playground

# distances in feet
feet = [70, 50, 102, 68, 86, 104, 100]

# TODO convert feet to metres if <= 100

metres = [dist/3.281 for dist in feet if dist <= 100]

print(metres)  # Output: [21.334958854007922, 15.239256324291373, 20.72538860103627, 26.21152087778116, 30.478512648582747]

[21.334958854007922, 15.239256324291373, 20.72538860103627, 26.21152087778116, 30.478512648582747]


<div class="alert alert-block alert-warning">
<b>🔽 Your Turn: 🔽 Underwater Robot Depth Tracking Based on Pressure </b><br><br>

In underwater exploration, robots continuously monitor depth changes by measuring pressure. Pressure increases with depth due to the weight of the water above, and it decreases as the robot ascends. Tracking the depth based on pressure changes is crucial for navigation and safety.

<u><b>Problem Statement:</b></u><br>
    A underwater robot monitors its depth by measuring pressure in Pascals. As the robot moves deeper into the water, the pressure increases, and as it ascends, the pressure decreases. Write a Python program that processes the pressure readings, which are given to you with the array <code> pressure </code> and determines whether the robot is ascending or descending.<br>

In detail the program should:
<ol>
        <li> Iterate through the pressure readings using enumerate and calculate whether the robot is ascending or descending: </li>
        <ul>
            <li> If the pressure increases between consecutive readings, the robot is descending and the output should be (-1). </li>
            <li> If the pressure decreases, the robot is ascending and the output should be (+1). </li>
            <li> If the pressure remains constant, it means no movement and the output should be (0). </li>
        </ul>
        <li> Append each movement status (-1 ,1 or 0) to a NumPy array called <code>movement_status</code>. </li>
        <li> Print both the original pressure readings and the movement status for each reading, except for the first one (as there's no previous data to compare).
</ol>

</div>

In [46]:
def track_robot_movement(pressure_readings):
    # Create an empty NumPy array to store movement status (-1, +1, 0)
    movement_status = np.array([])

    # Iterate through the pressure readings (starting from the second reading)
    for index, pressure in enumerate(pressure_readings[1:], start=1):
        # Compare the current pressure with the previous one
        previous_pressure = pressure_readings[index - 1]
        if pressure > previous_pressure:
            status = -1  # Descending
        elif pressure < previous_pressure:
            status = +1  # Ascending
        else:
            status = 0   # No change
        
        # Append the status to the movement_status array
        movement_status = np.append(movement_status, status)

    # Output the original pressure readings
    print("Original Pressure Readings:")
    for index, pressure in enumerate(pressure_readings):
        print(f"Index {index}: {pressure} Pa")

    # Output the movement status with their indices
    print("\nMovement Status:")
    for index, status in enumerate(movement_status, start=1):
        direction = "Descending" if status == -1 else "Ascending" if status == 1 else "No change"
        print(f"Index {index}: {status} ({direction})")

In [47]:
# Create a 5x5 dense matrix
dense_matrix = np.random.randint(0, 10, (5, 5))
print(dense_matrix)

# Initialize a list to store the sparse matrix elements
sparse_matrix_elements = []
test = []
test2 = []

# Iterate through the dense matrix
for i, row in enumerate(dense_matrix):
    for j, element in enumerate(row):
        if element > 3:
            sparse_matrix_elements = np.append(sparse_matrix_elements, [element, i, j])
            test.append([element, i, j])
            test2 += [[element, i, j]]
            # möglichkeit ohne reshape?


# Print the sparse matrix representation
print(sparse_matrix_elements[0])
print(sparse_matrix_elements)
sparse_matrix_elements = sparse_matrix_elements.reshape(-1, 3)
print(sparse_matrix_elements)

print(test)
print(test[0][0])
print(test[1][1])
print(test[-1][0])
print(test2)




[[9 0 4 8 0]
 [3 1 6 8 2]
 [5 4 2 3 6]
 [6 1 6 7 9]
 [4 4 5 4 6]]
9.0
[9. 0. 0. 4. 0. 2. 8. 0. 3. 6. 1. 2. 8. 1. 3. 5. 2. 0. 4. 2. 1. 6. 2. 4.
 6. 3. 0. 6. 3. 2. 7. 3. 3. 9. 3. 4. 4. 4. 0. 4. 4. 1. 5. 4. 2. 4. 4. 3.
 6. 4. 4.]
[[9. 0. 0.]
 [4. 0. 2.]
 [8. 0. 3.]
 [6. 1. 2.]
 [8. 1. 3.]
 [5. 2. 0.]
 [4. 2. 1.]
 [6. 2. 4.]
 [6. 3. 0.]
 [6. 3. 2.]
 [7. 3. 3.]
 [9. 3. 4.]
 [4. 4. 0.]
 [4. 4. 1.]
 [5. 4. 2.]
 [4. 4. 3.]
 [6. 4. 4.]]
[[np.int64(9), 0, 0], [np.int64(4), 0, 2], [np.int64(8), 0, 3], [np.int64(6), 1, 2], [np.int64(8), 1, 3], [np.int64(5), 2, 0], [np.int64(4), 2, 1], [np.int64(6), 2, 4], [np.int64(6), 3, 0], [np.int64(6), 3, 2], [np.int64(7), 3, 3], [np.int64(9), 3, 4], [np.int64(4), 4, 0], [np.int64(4), 4, 1], [np.int64(5), 4, 2], [np.int64(4), 4, 3], [np.int64(6), 4, 4]]
9
0
6
[[np.int64(9), 0, 0], [np.int64(4), 0, 2], [np.int64(8), 0, 3], [np.int64(6), 1, 2], [np.int64(8), 1, 3], [np.int64(5), 2, 0], [np.int64(4), 2, 1], [np.int64(6), 2, 4], [np.int64(6), 3, 0], [np.int64(6), 

In [48]:
def modify_temperatures(temperatures):
    # Create an empty NumPy array to store modified temperatures
    modified_temps = np.array([])

    # Loop through the original temperatures using enumerate
    for index, temp in enumerate(temperatures):
        # Modify the temperature based on the conditions
        if temp < 10:
            modified_temp = temp + 5
        elif temp > 35:
            modified_temp = temp - 5
        else:
            modified_temp = temp
        
        # Append the modified temperature to the new array
        modified_temps = np.append(modified_temps, modified_temp)

    # Output the original and modified temperatures with their indices
    print("Original Temperatures:")
    for index, temp in enumerate(temperatures):
        print(f"Index {index}: {temp}°C")

    print("\nModified Temperatures:")
    for index, temp in enumerate(modified_temps):
        print(f"Index {index}: {temp}°C")

# Example usage:
temperatures = [12, 8, 37, 15, 40]
modify_temperatures(temperatures)

Original Temperatures:
Index 0: 12°C
Index 1: 8°C
Index 2: 37°C
Index 3: 15°C
Index 4: 40°C

Modified Temperatures:
Index 0: 12.0°C
Index 1: 13.0°C
Index 2: 32.0°C
Index 3: 15.0°C
Index 4: 35.0°C


###  how to code? Plan steps, consider working your way up by starting with simpler problem, write sufficient comments (abschließender Tipp am ENde)

## am Ende nochmal Übersicht von allen Rechenoperationen, KOnventionen etc erneuter Verweis auf Numpz for Matlab users

***
other
- objektorientierte programmierung
- callback(listener)
- als aufgabe 0 integrieren
- referenz auf objekte (beispiel vielleicht)
- Funktionen deklarieren
- reshape doch mit reinnehmen, da in assignment 2?
- pip install numpy

In [49]:


fruits = ['apple', 'banana', 'cherry']
enum_fruits = enumerate(fruits)
 
next_element = next(enum_fruits)
print(f"Next Element: {next_element}")

next_element2 = next(enum_fruits)
print(f"Next Element: {next_element2}")


Next Element: (0, 'apple')
Next Element: (1, 'banana')


In [50]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(list(enumerate(matrix)))

for i, col in enumerate(matrix):
    for j, value in enumerate(col):
        print(f"Matrix[{i}][{j}] = {value}")


[(0, [1, 2, 3]), (1, [4, 5, 6]), (2, [7, 8, 9])]
Matrix[0][0] = 1
Matrix[0][1] = 2
Matrix[0][2] = 3
Matrix[1][0] = 4
Matrix[1][1] = 5
Matrix[1][2] = 6
Matrix[2][0] = 7
Matrix[2][1] = 8
Matrix[2][2] = 9
